# -*- coding: utf-8 -*-
"""api/index

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1szQoWaghuF3HMB1CeOjZzMvfyg_L0_gC
"""

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
import json
import numpy as np

app = FastAPI()

# Allow POST from any origin
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["POST"],
    allow_headers=["*"],
)

@app.post("/analytics")
async def analytics(request: Request):
    body = await request.json()
    regions = body.get("regions", [])
    threshold = body.get("threshold_ms", 999999)

    # Load telemetry file (place q-vercel-latency.json in repo root)
    with open("q-vercel-latency.json", "r") as f:
        telemetry = json.load(f)

    results = {}
    for region in regions:
        rows = [r for r in telemetry if r["region"] == region]
        if not rows:
            continue
        latencies = [r["latency_ms"] for r in rows]
        uptimes = [r["uptime_pct"] for r in rows]

        avg_latency = float(np.mean(latencies))
        p95_latency = float(np.percentile(latencies, 95))
        avg_uptime = float(np.mean(uptimes))
        breaches = sum(1 for r in rows if r["latency_ms"] > threshold)

        results[region] = {
            "avg_latency": avg_latency,
            "p95_latency": p95_latency,
            "avg_uptime": avg_uptime,
            "breaches": int(breaches),
        }

    return results